export type TourOpenGroup = 'startup' | 'reports' | 'management';

export type TourStep = {
  id: string;
  title: string;
  body: string;
  tip?: string;
  /** data-tour attribute value */
  target?: string;
  path?: string;
  openGroup?: TourOpenGroup;
  placement?: 'top' | 'bottom' | 'left' | 'right' | 'center';
};

export const ADMIN_TOUR_STEPS: TourStep[] = [
  {
    id: 'welcome',
    title: 'Panele hoş geldiniz',
    body: 'Birlikte panelin her köşesini gezeceğiz. Menü kurulumundan masa yönetimine kadar adım adım göstereceğim. İstediğiniz an “Atla” veya X ile çıkabilirsiniz.',
    tip: 'Tur yaklaşık 1–2 dakika sürer.',
    placement: 'center',
  },
  {
    id: 'menu-preview',
    title: 'Menüyü Gör',
    body: 'Müşterinin telefonunda gördüğü canlı menüyü buradan açarsınız. Ürün veya tema değiştirdikten sonra buraya basıp sonucu hemen kontrol edin.',
    tip: 'Yeni sekmede açılır; panel kapanmaz.',
    target: 'menu-preview',
    path: '/admin',
    placement: 'right',
  },
  {
    id: 'nav-ozet',
    title: 'Özet paneli',
    body: 'Günün nabzı burada: popüler ürünler, görüntülenmeler ve hızlı istatistikler. Sabah açıp “bugün ne oluyor?” diye bakmak için ideal yer.',
    target: 'nav-ozet',
    path: '/admin',
    placement: 'right',
  },
  {
    id: 'nav-groups',
    title: 'Gruplar',
    body: 'Menünün iskeleti burası. Burgerler, İçecekler, Kahvaltı gibi kategorileri oluşturur; sürükleyerek sıralar ve alt gruplar eklersiniz.',
    tip: 'Önce grupları kurun, sonra ürün eklemek çok daha kolay olur.',
    target: 'nav-groups',
    path: '/admin/groups',
    placement: 'right',
  },
  {
    id: 'nav-products',
    title: 'Ürünler',
    body: 'Her yemeği buraya eklersiniz: isim, fiyat, fotoğraf, açıklama, alerjen ve diyet etiketleri. Gruplara bağlayarak menüde doğru yerde görünmesini sağlarsınız.',
    target: 'nav-products',
    path: '/admin/products',
    placement: 'right',
  },
  {
    id: 'nav-showcase',
    title: 'Vitrin görselleri',
    body: 'Menünün üstündeki dikkat çekici banner ve hikâye görsellerini buradan yönetirsiniz. Kampanya veya öne çıkan ürün için kullanın.',
    target: 'nav-showcase',
    path: '/admin/showcase',
    placement: 'right',
  },
  {
    id: 'nav-barcode',
    title: 'Barkod yazdır',
    body: 'Her masa için QR kod üretirsiniz. Renk seçer, yazdırır ve masaya koyarsınız. Misafir kamerayla okutunca menü o masaya bağlanır.',
    tip: 'Salon / teras gibi masa gruplarını da buradan tanımlarsınız.',
    target: 'nav-barcode',
    path: '/admin/barcode',
    placement: 'right',
  },
  {
    id: 'nav-startup',
    title: 'Başlangıç ayarları',
    body: 'İlk izlenim burada şekillenir. Karşılama ekranı ve menü teması bu menünün altındadır — şimdi içine bakıyoruz.',
    target: 'nav-startup',
    path: '/admin',
    openGroup: 'startup',
    placement: 'right',
  },
  {
    id: 'nav-welcome-theme',
    title: 'Karşılama ekranı',
    body: 'QR okutulunca ilk açılan ekran. Dil seçimi, karşılama metni ve tema buradan ayarlanır. Markanızın “merhaba”sı burada.',
    target: 'nav-welcome-theme',
    path: '/admin/startup/welcome',
    openGroup: 'startup',
    placement: 'right',
  },
  {
    id: 'nav-menu-theme',
    title: 'Menü ekranı',
    body: 'Asıl menü görünümü: sade, canlı, lüks ve diğer temalar. Restoran tarzınıza uyanı seçip önizleyebilirsiniz.',
    tip: 'Bazı temalar Eklentiler’den açılır.',
    target: 'nav-menu-theme',
    path: '/admin/startup/menu',
    openGroup: 'startup',
    placement: 'right',
  },
  {
    id: 'nav-reports',
    title: 'Raporlar',
    body: 'İşletmenin kulağı burada. İstatistikler ve müşteri kutuları bu grubun altında — tek tek geziyoruz.',
    target: 'nav-reports',
    path: '/admin',
    openGroup: 'reports',
    placement: 'right',
  },
  {
    id: 'nav-stats',
    title: 'İstatistikler',
    body: 'Hangi ürün / grup ne kadar bakılmış, trend nasıl — grafikler ve sayılar burada. Menüyü neyin tuttuğunu anlarsınız.',
    target: 'nav-stats',
    path: '/admin/stats',
    openGroup: 'reports',
    placement: 'right',
  },
  {
    id: 'nav-suggestions',
    title: 'Öneri kutusu',
    body: 'Misafirlerin “şunu da ekleseniz” dediği mesajlar buraya düşer. Yeni ürün fikirleri için altın değerinde.',
    target: 'nav-suggestions',
    path: '/admin/suggestions',
    openGroup: 'reports',
    placement: 'right',
  },
  {
    id: 'nav-complaints',
    title: 'Şikayet kutusu',
    body: 'Olumsuz geri bildirimleri kaçırmadan okur ve takip edersiniz. Hızlı yanıt için günde bir kez bakmak iyi olur.',
    target: 'nav-complaints',
    path: '/admin/complaints',
    openGroup: 'reports',
    placement: 'right',
  },
  {
    id: 'nav-management',
    title: 'Yönetim',
    body: 'Panel kullanıcıları ve tüm sistem ayarları bu grubun altında. Konum kilidi de dahil birçok ayar Ayarlar’dadır.',
    target: 'nav-management',
    path: '/admin',
    openGroup: 'management',
    placement: 'right',
  },
  {
    id: 'nav-users',
    title: 'Kullanıcılar',
    body: 'Panele giren personeli buradan ekler veya yetkilerini yönetirsiniz. Garson / yönetici ayrımı için kullanın.',
    target: 'nav-users',
    path: '/admin/users',
    openGroup: 'management',
    placement: 'right',
  },
  {
    id: 'nav-settings',
    title: 'Ayarlar',
    body: 'Dil, para birimi, logo, sosyal medya, müzik, garson çağır ve konum kilidi gibi her şey burada. Restoran kimliğinin merkezi.',
    tip: 'Konum kilidi ile menüyü sadece mekân civarında açtırabilirsiniz.',
    target: 'nav-settings',
    path: '/admin/settings',
    openGroup: 'management',
    placement: 'right',
  },
  {
    id: 'extensions',
    title: 'Eklentiler',
    body: 'Ek temalar, dil paketi ve premium özellikler yapboz ikonundan açılır. Kod ile satın aldığınız eklentileri buradan aktifleştirirsiniz.',
    target: 'extensions',
    path: '/admin/extensions',
    placement: 'top',
  },
  {
    id: 'tour-help',
    title: 'Yardım her zaman burada',
    body: 'Bu soru işaretine her an tıklayıp turu yeniden başlatabilirsiniz. Yeni personel için de ideal.',
    target: 'tour-help',
    path: '/admin',
    placement: 'top',
  },
  {
    id: 'maintenance',
    title: 'Bakım modu',
    body: 'Menüyü geçici olarak kapatmak istediğinizde bu düğmeye basın. Misafirler menü yerine kısa bir bakım ekranı ve “Garson Koşusu” oyununu görür; siz işinizi bitirince tekrar kapatırsınız.',
    tip: 'Yenileme, tema değişimi veya acil durumlarda kullanın. Açıkken turuncu yanar.',
    target: 'maintenance',
    path: '/admin',
    placement: 'top',
  },
  {
    id: 'header-theme',
    title: 'Gündüz / gece',
    body: 'Panel temasını buradan değiştirirsiniz. Göz yormayan gece modu uzun nöbetlerde işe yarar.',
    target: 'header-theme',
    path: '/admin',
    placement: 'bottom',
  },
  {
    id: 'header-floor',
    title: 'Masa görünümü',
    body: 'Canlı salon haritası: dolu / boş masalar, süre, sipariş ekleme, rezervasyon, masa taşıma ve birleştirme burada.',
    tip: 'Servis sırasında en çok kullanacağınız ekranlardan biri.',
    target: 'header-floor',
    path: '/admin',
    placement: 'bottom',
  },
  {
    id: 'header-bell',
    title: 'Bildirimler',
    body: 'Garson çağrıları ve önemli uyarılar zilde birikir. Kırmızı nokta görürseniz bakmayı unutmayın.',
    target: 'header-bell',
    path: '/admin',
    placement: 'bottom',
  },
  {
    id: 'done',
    title: 'Hazırsınız!',
    body: 'Sıradaki pratik yol: Gruplar → Ürünler → Barkod yazdır → Menüyü Gör. Takılırsanız soru işaretine tekrar tıklamanız yeterli.',
    tip: 'İyi satışlar.',
    placement: 'center',
  },
];
